Updating symfony/flex  (#13589)
* Updating symfony/flex because ...

composer install fails with

Fatal error: Declaration of Symfony\Flex\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Composer\Command\RemoveCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /var/www/html/vendor/symfony/flex/src/Command/RemoveCommand.php on line 30

* Update redis-commander to a newer image

Signed-off-by: Priyanshi Gaur <noxdot1134@gmail.com>

---------

Signed-off-by: Priyanshi Gaur <noxdot1134@gmail.com>
Co-authored-by: Priyanshi Gaur <noxdot1134@gmail.com>